# Generated by Django 4.1.4 on 2022-12-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=5, unique=True)),
                ("domain", models.CharField(max_length=50)),
                ("link", models.CharField(max_length=255)),
            ],
        ),
    ]
