# Generated by Django 4.1.4 on 2022-12-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="domain",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
