# Generated by Django 4.1.4 on 2022-12-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_whois"),
    ]

    operations = [
        migrations.RenameField(
            model_name="whois",
            old_name="case_number",
            new_name="case_obj",
        ),
    ]
