# Generated by Django 4.1.4 on 2022-12-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_case_number_whois_case_obj"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="is_family",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="WhatCms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("res", models.JSONField()),
                (
                    "case_obj",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_whatcms_details",
                        to="user.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WappalyzerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("res", models.JSONField()),
                (
                    "case_obj",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_wappalyzer_details",
                        to="user.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("res", models.JSONField()),
                (
                    "case_obj",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_subdomain_details",
                        to="user.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SslCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("res", models.JSONField()),
                (
                    "case_obj",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_sslcertificate_details",
                        to="user.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NmapPort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("res", models.JSONField()),
                (
                    "case_obj",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_nmap_port_details",
                        to="user.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DnsEnum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("res", models.JSONField()),
                (
                    "case_obj",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_dns_enum_details",
                        to="user.case",
                    ),
                ),
            ],
        ),
    ]
