# Generated by Django 4.1.4 on 2022-12-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_case_is_family_whatcms_wappalyzermodel_subdomain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="ip_address",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
