# Generated by Django 4.1.4 on 2022-12-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_dnsenum_res_alter_nmapport_res_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OsScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("res", models.JSONField(blank=True, null=True)),
                (
                    "case_obj",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_os_scan_details",
                        to="user.case",
                    ),
                ),
            ],
        ),
    ]
