# Generated by Django 4.1.4 on 2023-01-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_malwarefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
