# Generated by Django 4.1.4 on 2023-02-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_casedetails_alter_dumpdata_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='phone_number_owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='phone_number_owner_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
