# Generated by Django 4.1.4 on 2023-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_casedetails_phone_number_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='is_whatsapp_active',
            field=models.BooleanField(default=False),
        ),
    ]
