# Generated by Django 4.1.4 on 2023-02-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_casedetails_is_whatsapp_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='breached_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='is_breached',
            field=models.BooleanField(default=False),
        ),
    ]
