# Generated by Django 4.1.4 on 2023-02-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_casedetails_breached_data_casedetails_is_breached'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseNumberLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=10)),
                ('numberlookup', models.TextField(blank=True, null=True)),
                ('casedetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.casedetails')),
            ],
        ),
    ]
