# Generated by Django 4.1.4 on 2023-02-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_reversenumberlookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='upiid_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
