# Generated by Django 4.1.4 on 2023-02-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_casedetails_upiid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='is_upi_verified',
            field=models.BooleanField(default=False),
        ),
    ]
