# Generated by Django 4.1.4 on 2023-02-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_casedetails_is_upi_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameLookUpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('namelookup', models.TextField(blank=True, null=True)),
                ('casedetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.casedetails')),
            ],
        ),
    ]
